### PR TITLE
Extended key joystick functionality + IKBD fixes

### LINKED ISSUE #119: Some keys in linux ce_conf act like Esc when they shouldn't
This shouldn't happen on CE_CONF.TOS and also doesn't happen on CE_CONF through web console. Happens under linux when using /ce/ce_conf.sh, and to reproduce it, you can do the following:
- go to some edit line, e.g. shared -> username
- delete chars using delete key
- press '0' (to write zero) and instead of writing 0 it jumps back to main menu. 

This is due to retarded way of reading and decoding the keys under linux ce_conf - so either fix this reading / decocing, or use something else than getchar() in getKey() function.

### PR DESCRIPTION
**Pull request by mikrosk**
I'll try to conclude all changes in this PR. Yes, I suck, I should have separated it into small patches.

1. Joystick translation can use generic keycodes, not only alphanumeric (ASCII). Right now you have to type it as following, I've decided not to implement another text field flag which would catch the scan codes directly as this would require major rework of the ST side as well. I've left out Eiffel keycodes as well for now. Namely you can type:
    - BACKSPACE, TAB, ENTER, LCTRL, LSHIFT, RSHIFT, LALT, CAPS, F1~F10, F11 (or HELP), F12 (or UNDO), HOME, UP, LEFT, RIGHT, DOWN, INSERT, DELETE
   - RCTRL, RALT (PC only)
   - KPMINUS, KPPLUS, KPLPARENT, KPRPARENT, KPSLASH, KPASTERISK, KP0~KP9, KPDOT, KPENTER (keypad)
1. Hotkey support for joy0/joy1 swap (**CTRL+any SHIFT+UNDO**), joy0 keyboard mapping (**CTRL+LSHIFT+HELP**) and joy1 keyboard mapping (**CTRL+RSHIFT+HELP**) ... so you can anytime swap joysticks, disable the mapping (for instance when you want to type your name) etc. I've decided not to swap keyboard mappings with joy0/joy1 as this introduces more chaos than good -- what to do if one of the mappings is off, what to do if we're in joystick mouse mode and so on...
1. CE_CONF disables joystick keyboard mapping -- especially important now, if you map UP/DOWN arrows as joystick movements
1. Improved navigation in CE_CONF -- **TAB** jumps to the first button and then goes forwards, **SHIFT+TAB** jumps to the last button and then goes backwards
1. Improved handling of linux scan codes, should definitely fix #119 
1. UNDO is equivalent to ESC = back to previous screen
1. Joystick fixes in mouse event reporting mode
1. Fixed enabling joystick event reporting for many commands (and vice versa, enabling mouse event reporting for mouse commands)

Some cleanup, some new bugs ;), you know the deal. I've tested it as much as humanly possible but only with a couple of games and own "unit tests" (Hi @atarijookie ! ;-))

Please merge (not squash) it.

### CODE REVIEW

**Comment by atarijookie** [comment]
Holy moly, that's a huge PR. Thanks for the work :+1: , we can merge this PR if anyone else is fine with this.

**Comment by mikrosk** [comment]
I guess @miniupnp should take a look first whether I haven't destroyed some of his USB code, I rebased my work on top of master (there were some conflicts, naturally) and tried to be careful but one never knows...

**Comment by miniupnp** [comment]
let me have a look

File: ce_main_app/ikbd/ikbd.h [hunk 1]
```diff
@@ -99,10 +105,20 @@ class Ikbd
...
     bool    keybJoy1;                       // if true, specific keys will act as joy 1
 
+    // this is basically all keys which are used for the hotswap, perhaps
+    // it should be made a bit more flexible, for different key combinations
+    int     leftShiftsPressed;  // how many LEFT SHIFTs are pressed (1x for PC, 1x for Atari)
+    int     rightShiftsPressed; // how many RIGHT SHIFTs are pressed (1x for PC, 1x for Atari)
+    int     ctrlsPressed;       // how many C[ON]TR[O]Ls are pressed (2x for PC, 1x for Atari)
+    int     f11sPressed;        // HELP on Atari, F11 on PC
+    int     f12sPressed;        // UNDO on Atari, F12 on PC
+    bool    waitingForHotkeyRelease;
```
Comment (miniupnp) [inline ce_main_app/ikbd/ikbd.h:120]: Why don't you use "pressedKeys" bitarray ? Maybe not possible because of Atari scan codes ?

File: ce_main_app/ikbd/ikbd_general.cpp [hunk 2]
```diff
@@ -225,7 +227,7 @@ Ikbd::Ikbd()
 void Ikbd::loadSettings(void)
 {
     Settings s;
-    bool firstJoyIs0 = s.getBool((char *) "JOY_FIRST_IS_0", false);
+    firstJoyIs0 = s.getBool((char *) "JOY_FIRST_IS_0", false);
```
Comment (miniupnp) [inline ce_main_app/ikbd/ikbd_general.cpp]: why cast to (char *) ?

File: ce_main_app/ikbd/ikbd_usb.cpp [hunk 3]
```diff
@@ -399,52 +399,51 @@ void Ikbd::processMouse(input_event *ev)
...
+            stKey = stKey | 0x80;
+            pressedKeys[ev->code] = false;
+        } else if (ev->value == 2) {
+            // auto repeat has no place on Atari! :)
             return;
         }
 
-        if(keybJoy0 && keyJoyKeys.isKeybJoyKeyPc(0, ev->code)) {    // Keyb joy 0 is enabled, and it's a keyb joy 0 key? Handle it specially.
-            handlePcKeyAsKeybJoy(0, ev->code, ev->value);
-            return;
```
Comment (miniupnp) [inline ce_main_app/ikbd/ikbd_usb.cpp:437]: the test `if(ev->code < KBD_KEY_COUNT) {` is now missing.

File: ce_main_app/ikbd/ikbd_usb.cpp [hunk 4]
```diff
@@ -399,52 +399,51 @@ void Ikbd::processMouse(input_event *ev)
...
+        pressedKeys[ev->code] = true;
```
Comment (miniupnp) [inline ce_main_app/ikbd/ikbd_usb.cpp]: isn't this code executed even if ev-value == 0 ?

**Comment by miniupnp** [comment]
I had made a few comments, It looks like you broke a couple of things. But I have no time to test now, I will have a deeper look and test on monday

**Review by miniupnp — CHANGES_REQUESTED** [review]
I had made a few comments, It looks like you broke a couple of things. But I have no time to test now, I will have a deeper look and test on monday

File: ce_main_app/ikbd/ikbd_usb.cpp (hunk 3 above)
Comment (miniupnp) [reply ce_main_app/ikbd/ikbd_usb.cpp:437]: hum I put the comment on the wrong line :) but I think you get it.
pressedKeys[ev->code] should not be accessed without checking (ev->code < KBD_KEY_COUNT). USB devices can send strange codes, I'm thinking of all theses "multimedia" USB Keyboards with extra keys. Pressing theses keys should not crash the CE...

File: ce_main_app/ikbd/ikbd.h (hunk 1 above)
Comment (mikrosk) [reply ce_main_app/ikbd/ikbd.h:120]: Because I was lazy (started only with ctrlPressed and shiftPressed), then the situation got out of hand and then you came with your elegant solution and I felt ashamed ;) (and was afraid to change it not to break anything -- remember, you're collecting only _USB_ keystrokes while I collect from both keyboards).

File: ce_main_app/ikbd/ikbd_general.cpp (hunk 2 above)
Comment (mikrosk) [reply ce_main_app/ikbd/ikbd_general.cpp]: No idea, as you can see, it was there before, I just made it a member variable...

File: ce_main_app/ikbd/ikbd_usb.cpp (hunk 3 above)
Comment (mikrosk) [reply ce_main_app/ikbd/ikbd_usb.cpp:437]: Yep, my fault. I did see that but I was like whaaat, this is useless. OK, it is _not_ useless. ;)

File: ce_main_app/ikbd/ikbd_usb.cpp (hunk 4 above)
Comment (mikrosk) [reply ce_main_app/ikbd/ikbd_usb.cpp]: Very, very good catch. This is a serious overlook from my side, thank you very much!

**Comment by mikrosk** [comment]
OK, I'm going to fix the things @miniupnp found, thanks mate.

File: ce_main_app/ikbd/ikbd.h (hunk 1 above)
Comment (miniupnp) [reply ce_main_app/ikbd/ikbd.h:120]: you're right. let is as it is at the moment. We'll do "atariPressedKeys / USBPressedKeys" later

**Review by miniupnp — APPROVED** [review]
looks OK now
